name: Deploy to EC2 with SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy code
      run: |
        sshpass -p ${{ secrets.EC2_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.EC2_IP_ADDRESS }}:/var/www/html/
